# Generated by Django 3.2.7 on 2026-04-15 06:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MindMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Untitled Mind Map', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Page 1', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mindmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='api.mindmap')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TextAnnotation',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('text', models.TextField(default='New Text')),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('font_size', models.IntegerField(default=16)),
                ('color', models.CharField(default='#334155', max_length=32)),
                ('font_weight', models.CharField(choices=[('normal', 'Normal'), ('bold', 'Bold')], default='normal', max_length=10)),
                ('font_style', models.CharField(choices=[('normal', 'Normal'), ('italic', 'Italic')], default='normal', max_length=10)),
                ('text_decoration', models.CharField(choices=[('none', 'None'), ('underline', 'Underline')], default='none', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='api.page')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Section', max_length=255)),
                ('color', models.CharField(default='#0EA5E9', max_length=32)),
                ('height', models.FloatField(default=400.0)),
                ('width', models.FloatField(blank=True, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.page')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('label', models.CharField(default='Node', max_length=1024)),
                ('color', models.CharField(default='#94A3B8', max_length=32)),
                ('points', models.IntegerField(default=3)),
                ('collapsed', models.BooleanField(default=False)),
                ('description', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='api.page')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.node')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='api.section')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('label', models.CharField(default='Frame', max_length=255)),
                ('color', models.CharField(default='#E2E8F0', max_length=32)),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('width', models.FloatField(default=200.0)),
                ('height', models.FloatField(default=150.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='api.page')),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('edge_type', models.CharField(choices=[('direct', 'Direct'), ('indirect', 'Indirect')], default='direct', max_length=16)),
                ('color', models.CharField(default='#94A3B8', max_length=32)),
                ('source_shape', models.CharField(choices=[('none', 'None'), ('line-arrow', 'Arrow'), ('triangle-arrow', 'Triangle'), ('circle', 'Circle')], default='none', max_length=32)),
                ('target_shape', models.CharField(choices=[('none', 'None'), ('line-arrow', 'Arrow'), ('triangle-arrow', 'Triangle'), ('circle', 'Circle')], default='none', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='api.page')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='api.node')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='api.node')),
            ],
            options={
                'unique_together': {('source', 'target')},
            },
        ),
    ]
